version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongoDB_clipzy
    volumes:
      - ./data/db:/data/db
  backend:
    build: ./backend
    container_name: clipzy_backend
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      S3_BUCKET: ${S3_BUCKET}
      MONGO_URI: mongodb://mongo:27017/clipzy
      AUTH_SECRET: ${AUTH_SECRET}
      JWT_SECRET: ${JWT_SECRET}
  frontend:
    build:
      context: ./frontend  
    container_name: clipzy_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_APP_URL=${VITE_APP_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
