version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongoDB_clipzy
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: always

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clipzy_backend
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app_network
    restart: always

volumes:
  mongodb_data:
