version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongoDB_clipzy
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always
  server:
    build: ./backend
    container_name: clipzy_backend
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      S3_BUCKET: ${S3_BUCKET}
      MONGO_URI: mongodb://mongo:27017/clipzy
      AUTH_SECRET: ${AUTH_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    
  frontend:
    build:
      context: ./frontend  
    container_name: clipzy_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    command: npm run dev -- --host 0.0.0.0  



