version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_clipzy
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always
  server:
    build: ./server
    container_name: clipzy_server
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      S3_BUCKET: ${S3_BUCKET}
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./server/thumbnails:/app/thumbnails
  frontend:
    build:
      context: ./client  # Verzeichnis zum Builden des Frontend
    container_name: clipzy_frontend
    ports:
      - "5173:5173"  # React App läuft standardmäßig auf Port 5173
    volumes:
      - ./client:/app  # Mounten des Frontend-Verzeichnisses
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    command: npm run dev -- --host 0.0.0.0  # Füge den Host hinzu, damit der Container verfügbar wird
