services:
  frontend:
    build:
      context: ./frontend  
    container_name: clipzy_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_APP_URL=${VITE_APP_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    command: npm start -- --host 0.0.0.0  



