name: Build and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout der Codebasis
      - name: Checkout code
        uses: actions/checkout@v2

      # Node.js Setup (falls notwendig)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Installiere Abhängigkeiten und baue das Projekt (Beispiel)
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Dieser Schritt könnte z.B. den Build in ./dist oder ./build erzeugen

      # Lade das Build-Verzeichnis als Artifact hoch
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-build-artifact  # Name des Artifacts
          path: ./dist  # Pfad zum Verzeichnis oder Datei, die hochgeladen werden soll
