name: Clipzy CI/CD Pipeline

on:
  push:
    branches: [main]
    
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 18
  BACKEND_PORT: 5000
  FRONTEND_PORT: 5173
  MONGODB_VERSION: 6

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:${{ env.MONGODB_VERSION }}
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: testuser
          MONGO_INITDB_ROOT_PASSWORD: testpass
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json

    # Backend Tests
    - name: Backend setup
      working-directory: ./backend
      run: |
        npm ci
        npm install ffmpeg-static

    - name: Run backend tests
      working-directory: ./backend
      env:
        MONGO_URI: mongodb://testuser:testpass@localhost:27017/clipzy-test
        JWT_SECRET: test-secret
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: npm test

    # Frontend Tests
    - name: Frontend setup
      working-directory: ./frontend
      run: npm ci

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    # Backend Image
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/clipzy-backend:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/clipzy-backend:${{ github.sha }}
        build-args: |
          NODE_ENV=production

    # Frontend Image
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/clipzy-frontend:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/clipzy-frontend:${{ github.sha }}